/* eslint key-spacing: 0 */
const attributes = (() => {
  const attrs = {
    'accept': null,
    'accept-charset': null,
    'accesskey': null,
    'action': null,
    'align': null,
    'alt': null,
    'async': null,
    'autocomplete': null,
    'autofocus': null,
    'autoplay': null,
    'autosave': null,
    'bgcolor': null,
    'border': null,
    'buffered': null,
    'challenge': null,
    'charset': null,
    'checked': null,
    'cite': null,
    // 'class': null, CLASS HAS OWN METHODS
    'code': null,
    'codebase': null,
    'color': null,
    'cols': null,
    'colspan': null,
    'content': null,
    'contenteditable': null,
    'contextmenu': null,
    'controls': null,
    'coords': null,
    'data': null,
    'datetime': null,
    'default': null,
    'defer': null,
    'dir': null,
    'dirname': null,
    'disabled': null,
    'download': null,
    'draggable': null,
    'dropzone': null,
    'enctype': null,
    'for': null,
    'form': null,
    'formaction': null,
    'headers': null,
    'height': null,
    'hidden': null,
    'high': null,
    'href': null,
    'hreflang': null,
    'http-equiv': null,
    'icon': null,
    'id': null,
    'ismap': null,
    'itemprop': null,
    'keytype': null,
    'kind': null,
    'label': null,
    'lang': null,
    'language': null,
    'list': null,
    'loop': null,
    'low': null,
    'manifest': null,
    'max': null,
    'maxlength': null,
    'media': null,
    'method': null,
    'min': null,
    'multiple': null,
    'muted': null,
    'name': null,
    'novalidate': null,
    'open': null,
    'optimum': null,
    'pattern': null,
    'ping': null,
    'placeholder': null,
    'poster': null,
    'preload': null,
    'radiogroup': null,
    'readonly': null,
    'rel': null,
    'required': null,
    'reversed': null,
    'rows': null,
    'rowspan': null,
    'sandbox': null,
    'scope': null,
    'scoped': null,
    'seamless': null,
    'selected': null,
    'shape': null,
    'size': null,
    'sizes': null,
    'span': null,
    'spellcheck': null,
    'src': null,
    'srcdoc': null,
    'srclang': null,
    'srcset': null,
    'start': null,
    'step': null,
    'style': null,
    'summary': null,
    'tabindex': null,
    'target': null,
    'title': null,
    'type': null,
    'usemap': null,
    'value': null,
    'width': null,
    'wrap': null,
  }

  return attrname => {
    if (typeof attrs[attrname] === 'undefined')
      return false
    return attrs[attrname]
  }

})

export default attributes
