/* eslint key-spacing: 0 */
import { COLOR, LENGTH } from './constants'

const cssprops = (() => {
  const props = {
    'background': null,
    'backgroundAttachment': null,
    'backgroundColor': COLOR,
    'backgroundImage': null,
    'backgroundPosition': null,
    'backgroundRepeat': null,
    'border': null,
    'borderBottom': null,
    'borderBottomColor': COLOR,
    'borderBottomStyle': null,
    'borderBottomWidth': LENGTH,
    'borderColor': COLOR,
    'borderLeft': null,
    'borderLeftColor': COLOR,
    'borderLeftStyle': null,
    'borderLeftWidth': LENGTH,
    'borderRadius': LENGTH,
    'borderRight': null,
    'borderRightColor': COLOR,
    'borderRightStyle': null,
    'borderRightWidth': LENGTH,
    'borderStyle': null,
    'borderTop': null,
    'borderTopColor': COLOR,
    'borderTopStyle': null,
    'borderTopWidth': LENGTH,
    'borderWidth': LENGTH,
    'bottom': LENGTH,
    'boxShadow': null,
    'clear': null,
    'clip': null,
    'color': COLOR,
    'cursor': null,
    'display': null,
    'filter': null,
    'font': null,
    'fontFamily': null,
    'fontSize': LENGTH,
    'fontVariant': null,
    'fontWeight': null,
    'height': LENGTH,
    'left': LENGTH,
    'letterSpacing': LENGTH,
    'lineHeight': LENGTH,
    'listStyle': null,
    'listStyleImage': null,
    'listStylePosition': null,
    'listStyleType': null,
    'margin': LENGTH,
    'marginBottom': LENGTH,
    'marginLeft': LENGTH,
    'marginRight': LENGTH,
    'marginTop': LENGTH,
    'opacity': null,
    'outline': null,
    'overflow': null,
    'padding': LENGTH,
    'paddingBottom': LENGTH,
    'paddingLeft': LENGTH,
    'paddingRight': LENGTH,
    'paddingTop': LENGTH,
    'pageBreakAfter': null,
    'pageBreakBefore': null,
    'position': null,
    'cssFloat': null,
    'right': LENGTH,
    'textAlign': null,
    'textDecoration': null,
    'textDecorationBlink': null,
    'textDecorationLineThrough': null,
    'textDecorationNone': null,
    'textDecorationOverline': null,
    'textDecorationUnderline': null,
    'textIndent': null,
    'textTransform': null,
    'top': LENGTH,
    'verticalAlign': null,
    'visibility': null,
    'width': LENGTH,
    'zIndex': null,
  }

  return propname => {
    if (typeof props[propname] === 'undefined')
      return false
    return props[propname]
  }

})

export default cssprops
